apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: social-media
type: Opaque
stringData:
  DB_PASSWORD: ${DB_PASSWORD}
  REDIS_PASSWORD: ${REDIS_PASSWORD}
  JWT_SECRET: ${JWT_SECRET}
  CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}